import type { LevelDefinition } from '../engine/types';

// Legend: # wall | . empty | O orb | B block | X goal
// All boards are 8x8. Each level's optimalMoves is BFS-verified (see /mnt/skills — generated via scripted solver).

export const LEVELS: LevelDefinition[] = [
  {
    id: 1,
    name: "First Slide",
    optimalMoves: 2,
    grid: [
      "########",
      "#O.....#",
      "#......#",
      "#......#",
      "#......#",
      "#......#",
      "#.....X#",
      "########",
    ],
  },
  {
    id: 2,
    name: "Wall Stop",
    optimalMoves: 3,
    grid: [
      "########",
      "#.O....#",
      "#..#...#",
      "#......#",
      "#..#..##",
      "#.....X#",
      "#......#",
      "########",
    ],
  },
  {
    id: 3,
    name: "Split Path",
    optimalMoves: 3,
    grid: [
      "########",
      "#.O.#..#",
      "#..#...#",
      "#.#....#",
      "#......#",
      "#......#",
      "#...X..#",
      "########",
    ],
  },
  {
    id: 4,
    name: "Corner Pocket",
    optimalMoves: 3,
    grid: [
      "########",
      "#...#..#",
      "#..X#..#",
      "#.O....#",
      "#..#...#",
      "#......#",
      "#......#",
      "########",
    ],
  },
  {
    id: 5,
    name: "The Long Way",
    optimalMoves: 4,
    grid: [
      "########",
      "#...#..#",
      "#..#...#",
      "#..X...#",
      "##.....#",
      "#.O....#",
      "#......#",
      "########",
    ],
  },
  {
    id: 6,
    name: "Handy Block",
    optimalMoves: 4,
    grid: [
      "########",
      "#.....##",
      "#...#..#",
      "#.O....#",
      "#.B....#",
      "#......#",
      "#.X....#",
      "########",
    ],
  },
  {
    id: 7,
    name: "Set the Stopper",
    optimalMoves: 4,
    grid: [
      "########",
      "#.X....#",
      "#...#..#",
      "#......#",
      "#.B....#",
      "#.O....#",
      "#....#.#",
      "########",
    ],
  },
  {
    id: 8,
    name: "Corner Block",
    optimalMoves: 4,
    grid: [
      "########",
      "#....X.#",
      "#...#..#",
      "#......#",
      "##B....#",
      "#......#",
      "#...O..#",
      "########",
    ],
  },
  {
    id: 9,
    name: "Double Back",
    optimalMoves: 6,
    grid: [
      "########",
      "#......#",
      "#.B.#.##",
      "#......#",
      "#......#",
      "#...X..#",
      "#O.....#",
      "########",
    ],
  },
  {
    id: 10,
    name: "Around the Bend",
    optimalMoves: 6,
    grid: [
      "########",
      "#......#",
      "#.X.#..#",
      "#......#",
      "##...B.#",
      "#..O...#",
      "#......#",
      "########",
    ],
  },
  {
    id: 11,
    name: "Two Helpers",
    optimalMoves: 6,
    grid: [
      "########",
      "##.....#",
      "#O.....#",
      "#...X..#",
      "#....#.#",
      "#...BB.#",
      "#..#...#",
      "########",
    ],
  },
  {
    id: 12,
    name: "Traffic Jam",
    optimalMoves: 6,
    grid: [
      "########",
      "##.....#",
      "#B.#O..#",
      "#......#",
      "#......#",
      "#.#.B..#",
      "#X.....#",
      "########",
    ],
  },
  {
    id: 13,
    name: "Tight Fit",
    optimalMoves: 6,
    grid: [
      "########",
      "#.#....#",
      "##.....#",
      "#..BO..#",
      "#......#",
      "#.#....#",
      "#X..B..#",
      "########",
    ],
  },
  {
    id: 14,
    name: "Zig Zag",
    optimalMoves: 6,
    grid: [
      "########",
      "#.#...X#",
      "#......#",
      "#..#...#",
      "#...B..#",
      "#....#.#",
      "#O..B..#",
      "########",
    ],
  },
  {
    id: 15,
    name: "Three's Company",
    optimalMoves: 7,
    grid: [
      "########",
      "##B...X#",
      "#.....B#",
      "#...#..#",
      "#......#",
      "#......#",
      "#O#....#",
      "########",
    ],
  },
  {
    id: 16,
    name: "Boxed In",
    optimalMoves: 8,
    grid: [
      "########",
      "##.....#",
      "#.....O#",
      "#...#..#",
      "#B...B.#",
      "#..#X.##",
      "#B.....#",
      "########",
    ],
  },
  {
    id: 17,
    name: "Chain Reaction",
    optimalMoves: 8,
    grid: [
      "########",
      "#B...#.#",
      "#B.....#",
      "#O.....#",
      "#......#",
      "#...#X##",
      "#.B..#.#",
      "########",
    ],
  },
  {
    id: 18,
    name: "Precision Slide",
    optimalMoves: 8,
    grid: [
      "########",
      "#..#...#",
      "#....B.#",
      "#......#",
      "#.X...B#",
      "#.B#O.##",
      "#..#...#",
      "########",
    ],
  },
  {
    id: 19,
    name: "Blockade",
    optimalMoves: 8,
    grid: [
      "########",
      "#....B.#",
      "#B.....#",
      "#......#",
      "#....#B#",
      "#..#..##",
      "#O..#X.#",
      "########",
    ],
  },
  {
    id: 20,
    name: "The Final Shift",
    optimalMoves: 11,
    grid: [
      "########",
      "#.....B#",
      "#.B...B#",
      "#......#",
      "#......#",
      "###.#X.#",
      "#.O..#.#",
      "########",
    ],
  },
];

export function getLevel(id: number): LevelDefinition | undefined {
  return LEVELS.find((l) => l.id === id);
}
